# Generated by Django 3.1.5 on 2021-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210121_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default=None, max_length=150, verbose_name='Автор'),
        ),
    ]
